{{- if eq (.Values.mode | default "manager") "manager" }}
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fishkube.fullname" . }}-config
  labels:
    {{- include "fishkube.labels" . | nindent 4 }}
{{- end }}
