{{- if .Values.ingress.enabled -}}
# SPDX-License-Identifier: Apache-2.0
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fishkube-manager
  {{- $hasAnnotations := or .Values.ingress.annotations .Values.ingress.className }}
  {{- if $hasAnnotations }}
  annotations:
    {{- if and .Values.ingress.className (not (and .Values.ingress.annotations (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class"))) }}

    {{- end }}
    {{- with .Values.ingress.annotations }}
{{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: fishkube-manager
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
{{- end -}}